from .backends import DGLAdapter, PyGAdapter, get_backend
from .core import (
    Explainer,
    Explanation,
    compare,
    get_algorithm,
    instantiate,
    register,
    report_html,
)
from .core.evaluation import (
    evaluate_fidelity_minus,
    evaluate_fidelity_plus,
    evaluate_gea,
    evaluate_gea_graph,
    evaluate_sparsity,
    evaluate_stability,
)
from .methods import (
    AttentionExplainer,
    Counterfactual,
    DeepLift,
    GNNExplainer,
    GNNGatedLRP,
    GradXInput,
    GraphLIME,
    GuidedBackprop,
    IntegratedGradients,
    NodeMask,
    PGExplainer,
    RandomBaseline,
    Saliency,
    SubgraphX,
)
from .narration import Narrator, describe, narrate, summarize
from .visualization import show, visualize_interactive, visualize_static

__version__ = "0.7.0"

__all__ = [
    "AttentionExplainer",
    "Counterfactual",
    "DGLAdapter",
    "DeepLift",
    "Explainer",
    "Explanation",
    "GNNExplainer",
    "GNNGatedLRP",
    "GradXInput",
    "GraphLIME",
    "GuidedBackprop",
    "IntegratedGradients",
    "Narrator",
    "NodeMask",
    "PGExplainer",
    "PyGAdapter",
    "RandomBaseline",
    "Saliency",
    "SubgraphX",
    "__version__",
    "compare",
    "describe",
    "evaluate_fidelity_minus",
    "evaluate_fidelity_plus",
    "evaluate_gea",
    "evaluate_gea_graph",
    "evaluate_sparsity",
    "evaluate_stability",
    "get_algorithm",
    "get_backend",
    "instantiate",
    "narrate",
    "register",
    "report_html",
    "show",
    "summarize",
    "visualize_interactive",
    "visualize_static",
]
